language: node_js
node_js:
- '4.2'
install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
script:
- npm run build:test
deploy:
  provider: npm
  on: 
    tags: true
  skip_cleanup: true
  email : pawel.gutkowski.1993@gmail.com
  api_key:
    secure: $API_KEY
